apiVersion: v1
kind: Service
metadata:
  name: go-weather-notify-service
spec:
  type: NodePort
  selector:
    app: go-weather-notify
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
